name: Waka Readme

on:
  schedule:
    # Körs varje natt klockan 00:00
    - cron: '0 0 * * *'
  workflow_dispatch: # Ger en knapp för att köra den manuellt

jobs:
  update-readme:
    name: Update Readme with WakaTime Stats
    runs-on: ubuntu-latest
    # VI UTÖKAR DENNA SEKTION FÖR ATT VARA TYDLIGARE
    permissions:
      contents: write
      pull-requests: read
      
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHOW_DAYS_OF_WEEK: "true"
          SHOW_LANGUAGE: "true"
          SHOW_TOTAL_CODE_TIME: "true"
          SHOW_PROFILE_VIEWS: "false"
          SHOW_LOC_CHART: "false"
