name: Waka Readme

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with WakaTime Stats
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
      
    steps:
      - uses: anmol098/waka-readme-stats@v4
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHOW_DAYS_OF_WEEK: "true"
          SHOW_LANGUAGE: "true"
          # Raden nedan är borttagen
          # SHOW_TOTAL_CODE_TIME: "true" 
          SHOW_PROFILE_VIEWS: "false"
          SHOW_LOC_CHART: "false"
