name: Waka Readme

on:
  workflow_dispatch: # Tillåter manuell körning
  schedule:
    - cron: '0 0 * * *' # Körs varje dag vid midnatt

jobs:
  update-readme:
    name: Update Readme with Waka Stats
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHOW_TITLE: true
          SHOW_DAYS_OF_WEEK: true
          SHOW_TIMEZONE: false
          SHOW_EDITORS: false
          SHOW_PROJECTS: false
          SHOW_OS: false
          SHOW_LANGUAGE_PER_REPO: false
