name: Waka Readme

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with WakaTime Stats
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
      
    steps:
      # Vi går tillbaka till @master nu när behörigheterna är fixade
      - uses: anmol098/waka-readme-stats@master
        with:
          # Vi behöver inte USERNAME, @master hittar dig automatiskt
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Vi lägger tillbaka den parameter som @master förstår
          SHOW_TOTAL_CODE_TIME: "true"
          SHOW_DAYS_OF_WEEK: "true"
          SHOW_LANGUAGE: "true"
          SHOW_PROFILE_VIEWS: "false"
          SHOW_LOC_CHART: "false"
