name: Waka Readme Stats

on:
  schedule:
    # Körs varje natt
    - cron: '0 0 * * *'
  workflow_dispatch: # Ger en knapp för att köra den manuellt

jobs:
  update-readme:
    name: Update Readme with WakaTime Stats
    runs-on: ubuntu-latest
    # Viktigt: Korrekta behörigheter som vi löste tidigare
    permissions:
      contents: write
      pull-requests: read

    steps:
      # Vi använder @master som är den moderna, fungerande versionen
      - uses: anmol098/waka-readme-stats@master
        with:
          # Notera: Ingen USERNAME behövs, @master hittar dig automatiskt
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          # Här är några vanliga och fungerande alternativ:
          SHOW_TOTAL_CODE_TIME: "true"
          SHOW_DAYS_OF_WEEK: "true"
          SHOW_LANGUAGE: "true"
          SHOW_PROFILE_VIEWS: "false"
