name: Waka Readme

on:
  workflow_dispatch: # Tillåter manuell körning
  schedule:
    - cron: '0 0 * * *' # Körs varje dag vid midnatt

jobs:
  update-readme:
    name: Update Readme with Waka Stats
    runs-on: ubuntu-latest
    steps:
    - uses: anmol098/waka-readme-stats@master
      with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHOW_DAYS_OF_WEEK: "true"       # Visar vilken dag du är mest produktiv
          SHOW_LANGUAGE: "true"           # Visar dina mest använda språk
          SHOW_TOTAL_CODE_TIME: "true"  # Visar den totala tiden du kodat
          SHOW_PROFILE_VIEWS: "false"     # Stänger av visningsräknaren (valfritt)
          SHOW_LOC_CHART: "false"         # Stänger av en annan typ av graf (valfritt)
